import React from 'react'
import { Container } from '@radix-ui/themes'
import { type Metadata } from 'next'
import Link from 'next/link'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Next Auth Radix',
  description: 'Generated by create next app'
}
const HomePage = async () => {
  const session = await getServerSession(authOptions)

  if (session) {
    redirect('/dashboard')
  }
  return (
    <Container className='px-10 md:px-0'>
      <header className='my-4 bg-slate-900 text-white p-10 rounded-md'>
        <h1 className='text-7xl my-10'>Next Auth Radix</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Culpa asperiores maxime amet doloremque porro explicabo autem expedita sed ipsum fugit possimus in rerum delectus eaque nulla libero at tempora beatae, eum unde fugiat nostrum necessitatibus. Ut in modi non eum sunt earum, est laborum debitis! Sunt, ex? Non temporibus quas assumenda eum, cupiditate ad maxime aut quia voluptas corrupti accusantium, autem provident sequi exercitationem tenetur deleniti adipisci, maiores blanditiis recusandae!</p>
        <div className="mt-5">
          <Link href={'/auth/login'} className='bg-blue-500 text-white py-2 rounded-md px-2'>Ingresa</Link>
        </div>
      </header>
    </Container>
  )
}

export default HomePage
